{
 "title": "Rabbit Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "rabbit_cpu_load_percent", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Storage usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "rabbit_storage_percent", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "rabbit_memory_percent", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Network Download usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    { "expr": "rabbit_network_eth0_download", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Swap usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "rabbit_swap_percent", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Network Upload usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    { "expr": "rabbit_network_eth0_upload", "legendFormat": "{{job}}" }
   ]
  }
 ]
}